### ISSUE TITLE
Variables are not being replaced

### ISSUE THREAD

**Issue by albertczyk** [advanced-rest-client/request-engine#1]
*   Application version: 15.0.7
*   Operating System: Linux (Fedora 31)

**Expected Behavior**
Variables should be replaced in URLs and headers.

**Actual behavior**
Variables are not replaced at all, despite having been properly defined in the active environment.

**To Reproduce**
Define a variable like i.e. 'host' in the current environment, then use it in the endpoint URL
Launch the request - the variable is not replaced

**Screenshots**
![image](https://user-images.githubusercontent.com/22469595/92258829-520a2f80-eed7-11ea-9f3c-c0dab14550a1.png)

**Additional Information**
This began to happen after upgrading from a quite ancient version where this worked fine (probably 8) to 15.
Installed from rpm with 'rpm -hiv https://github.com/advanced-rest-client/arc-electron/releases/download/v15.0.7/arc-linux-15.0.7-x86_64.rpm', though it happens the same when cloning the repository and starting with npm start.
I've seen no other references to this bug, so maybe it's related to some system or library issue. Anyway, I've tried to clean up all config files and reinstall from scratch, and the problem still appears. It's clearly a Linux issue, as the same version in Windows it's working fine.

It looks like the event launched when the request is sent has no 'config' object set (it should be a property of the dispatched event), so any further processing of the variables is not performed. I'm not very familiar with the code, but I'll dig a bit more to see if I find out something more.
![image](https://user-images.githubusercontent.com/22469595/94034974-e115b380-fdc2-11ea-98cd-b9ae13a53cc7.png)

![image](https://user-images.githubusercontent.com/22469595/94034637-8bd9a200-fdc2-11ea-94e4-da21b6f105d0.png)

**Comment by albertczyk** [comment]
No problem, I understand it's a really complex development, and a superb tool! Many thanks for your work!

**Comment by jarrodek** [comment]
This is now fixed and tested here: https://github.com/advanced-rest-client/request-engine/blob/main/test/RequestFactory.test.js#L206

The application will be released when this PR is merged: https://github.com/advanced-rest-client/arc-electron/pull/327
